<?php
  require_once 'vendor/autoload.php';


  if($_SERVER['REQUEST_METHOD'] == "POST"){
    @extract($_POST);
    echo validationChk($email);
  }
  // This file is generated by Composer
  function validationChk($email) {
    $api = '9f7d48c83e6b84af8f78aecbcda11febf241983c2002876e138efa871595';
    $client   = new QuickEmailVerification\Client($api);
    $quickemailverification  = $client->quickemailverification();
    try {
    // PRODUCTION MODE
      $response = $quickemailverification->verify($email);
      return json_encode($response);
    // SANDBOX MODE
    // $response = $quickemailverification->sandbox("valid@example.com");
    }
    catch (Exception $e) {
      return "Code: " . $e->getCode() . " Message: " . $e->getMessage();
    }
  }





?>
